### ISSUE TITLE
Fullscreen support

### ISSUE THREAD

**Issue by benswift** [rikusalminen/glwt#10]
In #2 you discuss fullscreen support and say that it's a tricky problem—I agree :)

Has there been any developments on this front?  I'm open to contributing code, but I wanted to know if there had been any more thoughts on how best to do it.

**Comment by rikusalminen** [comment]
No, there has not been any development in this front. Please do contribute if you can.

The API should look something like `glwtFullscreen(window, mode)`. We want a function to change the mode rather than setting it when creating a window.

The preferred way to do full screen in X11 is using the WM_FULLSCREEN, which is a part of the extended window manager hints (EWMH). EWMH also provides an event when a window is full screened, because this can be initiated by the window manager. (this is a reason why I have not needed the feature, my window manager can full screen any window).

For Windows and OSX, I do not know what the preferred way to do full screen is. We're initially interested in "windowed" or "soft" full screen. A "hard" full screen mode has non-trivial interaction with monitor APIs, screen resolutions, etc.

Another related feature is window resizability and window min/max size limits.
