### ISSUE TITLE
cmake BUILD_SHARED_LIBS=TRUE option

### ISSUE THREAD

**Issue by benswift** [rikusalminen/glwt#11]
Currently, building shared libs is disallowed—is there any reason for this? Fair enough to have `FALSE` as the default, but it would be nice to not have the option disallowed (meaning that I have to resort to a patch to `CMakeLists.txt`).

**Comment by rikusalminen** [comment]
The reason is that we have not set up proper dllexport/dllimport linkage for exported symbols (this is only required on Windows by default). That shouldn't be too hard to do, but it has not been a priority for us.

Feel free to contribute a patch for this.

**Comment by benswift** [comment]
Ok, thanks for the heads up.  I don’t have a windows box handy to test on at the moment, but if I can get my hands on one I’ll try and put together a patch.

Cheers,
Ben

**Comment by rikusalminen** [comment]
Yes, Windows is a pain in the ass for us because none of us use Windows on a daily basis. We're also trying to support MSVC compiler which is also a bit painful.

In any case, you should be able to write the code and test that it works even if you don't have a Windows box at hand. dllexport/dllimport also work with GCC-mingw cross compiling. But the code will have to be compiled and tested on MSVC and Windows before it can be merged to master.

In addition to dllimport/dllexport, you'll also need to set up SOVERSION in CMakeLists.txt to get proper filenames and symlinks set up.

Thanks for the effort, I'll be waiting for the patches to appear!

**Comment by benswift** [comment]
Cool, thanks for the heads up.  When the current release is out the door I’ll have a poke around.

Cheers,
Ben
