### ISSUE TITLE
A few ideas...

### ISSUE THREAD

**Issue by r-lyeh-archived** [rikusalminen/glwt#2]
A few ideas
- rename &lt;GLWT/glwt.h&gt; to &lt;GL/glwt.h&gt; ; glew, glut, glfw, freeglut etc look like this
- add true fullscreen support (glfw does it right)
- add windowed fullscreen support (freeglut does it almost right)
- allow apps to review/modify/cancel system event messages by calling an user-defined callback in glwtEventHandle()
- add float glwtWindowGetFps(win*); number of frames per second
- add float glwtWindowGetDelta(win*); seconds lapsed since last render 
- add double glwtGetTime(); seconds lapsed since glwt Init

Keep up the good work

**Comment by rikusalminen** [comment]
Thanks for the comments, some of your suggestions make perfect sense, others not so much.

> rename to ; glew, glut, glfw, freeglut etc look like this - yes, I know.

The naming was intentional, let's stick to the glXX tradition. We had a long discussion about that just before I created this GitHub repo. GLWT can stand for "good luck with that" or "glut with double u".

> add true fullscreen support (glfw does it right)

You mean true full screen as in set hardware video mode and make window full screen? Yes, that makes sense but we'd need more thorough support for resolutions, multiple monitors, etc. Almost no software lib does this right - e.g. SDL gives me a window that is half on my left monitor and half on the right. So yes, let's do this but it's a rather big feature and not easy to get right and portable.

> add windowed fullscreen support (freeglut does it almost right)

Definitely yes. On X11 this should use the WM_FULLSCREEN extended window manager hint, which already covers 99% of full screen use cases. Almost all window managers support this.

> allow apps to review/modify/cancel system event messages by calling an user-defined callback in glwtEventHandle()

I'm not sure how this should work. GLWT event handling is intentionally as small a wrapper as possible that passes the events as-is to from the windowing system to the user. The events (in particular, their order) might not work identically on all platforms either (I don't think it's possible to implement in a sane manner).

> add float glwtWindowGetFps(win*); number of frames per second
> 
> add float glwtWindowGetDelta(win*); seconds lapsed since last render 

I do not agree on these. GLWT is designed to be stateless and simple as far as possible. I understand why such convenience features would be nice but an FPS counter is really simple to implement on the user side, so I don't see the need for that.

And besides, FPS is a terrible metric for benchmarking, most people should be using GL_TIME_ELAPSED query instead.

> add double glwtGetTime(); seconds lapsed since glwt Init

Yes, a timer is probably a good idea. I'm not sure how to implement it on Win32, but all the other platforms could use clock_gettime(CLOCK_MONOTONIC) from POSIX.

I think the return value should be a 64 bit unsigned integer, in nanoseconds and the absolute value should be meaningless (so GLWT would be stateless where possible).

Can you please investigate what is the best way to get a monotonic timestamp on win32? Monotonic meaning that it always increases and changing wall clock time, timezones, etc should have no effect on the value.

Thank you for your feedback, let's keep this issue open for future idea planning!

**Comment by r-lyeh-archived** [comment]
GetTickCount64() will do. its a monotonic millisecond-resolution timer that wraps once in lifetime :dancer:

**Comment by rikusalminen** [comment]
Unfortunately it's not quite that simple, since the timer is not guaranteed to start from zero, so you still have to think about wraparound, although that is very rare. Maybe we should complement it with a function to compute the time interval between two timestamps.

Note: 2^64 nanoseconds is roughly 584 years.

**Comment by rikusalminen** [comment]
Closing this issue. (some) of these things are being worked on.  I might open some issues for individual features later on.
